In [2]:
#np.concatenate 连接两个数组：
import numpy as np
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr=np.concatenate((arr1,arr2))
arr3=arr1+arr2
print(arr,arr3)

[1 2 3 4 5 6] [5 7 9]


In [6]:
import numpy as np

arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)

print(arr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [12]:
import numpy as np

arr1 = np.array([[1, 2], [3, 4],['a','b']])
arr2 = np.array([[5, 6], [7, 8],['a','b']])
arr = np.concatenate((arr1, arr2), axis=1)

print(arr)

[['1' '2' '5' '6']
 ['3' '4' '7' '8']
 ['a' 'b' 'a' 'b']]


In [20]:
#np.stack
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])
arr3 = np.array([7, 8, 9])

arr = np.stack((arr1, arr2,arr3), axis=1)

print(arr)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [23]:
#NumPy 提供了一个辅助函数：hstack() 沿行堆叠
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])
arr3 = np.array([7, 8, 9])
arr = np.hstack((arr1, arr2,arr3))

print(arr)

[1 2 3 4 5 6 7 8 9]


In [25]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])
arr3 = np.array([7, 8, 9])
arr = np.vstack((arr1, arr2,arr3))

print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [28]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr3 = np.array([7, 8, 9])
arr = np.dstack((arr1, arr2,arr3))

print(arr)

[[[1 4 7]
  [2 5 8]
  [3 6 9]]]


In [34]:
#拆分 NumPy 数组 如果数组中的元素少于要求的数量，它将从末尾进行相应调整
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6,7,8,9])

newarr = np.array_split(arr, 3)
a=newarr[1]
print(newarr)
print(a)

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]
[4 5 6]


In [40]:
提示：我们也有 split() 方法可用，
但是当源数组中的元素较少用于拆分时
，它将不会调整元素，
如上例那样，array_split() 正常工作，
但 split() 会失败。

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]


In [42]:
#拆分二维数组时，请使用相同的语法
import numpy as np

arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8],[9, 10], [9, 10], [11, 12]])

newarr = np.array_split(arr, 3)

print(newarr)

[array([[1, 2],
       [3, 4],
       [5, 6]]), array([[ 7,  8],
       [ 9, 10]]), array([[ 9, 10],
       [11, 12]])]


In [48]:

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3, axis=1)

print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [51]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.hsplit(arr, 3)

print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [59]:
import numpy as np

arr = np.array([4,4,4,4,4,4,23,23,13,12,315,4])

x = np.where(arr == 4)

print(x)

(array([ 0,  1,  2,  3,  4,  5, 11], dtype=int64),)


In [61]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)


arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 1)

print(x)

(array([3, 5, 6], dtype=int64),)
(array([0, 2, 4, 6], dtype=int64),)


In [65]:
import numpy as np

arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 9)

print(x)
 
arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 6, side='right')

print(x)

3
1


In [67]:
import numpy as np

arr = np.array([1, 3, 5, 7])

x = np.searchsorted(arr, [2, 4, 6])

print(x)


[1 2 3]
[1 3 5 7]


In [71]:
#排序
import numpy as np

arr = np.array([3, 2, 0, 1])

print(np.sort(arr))
 

arr = np.array(['banana', 'cherry', 'apple'])

print(np.sort(arr))
 

arr = np.array([True, False, True])

print(np.sort(arr))
 

arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))

[0 1 2 3]
['apple' 'banana' 'cherry']
[False  True  True]
[[2 3 4]
 [0 1 5]]


In [72]:
arr = np.array([61, 62, 63, 64, 65])

x = [True, False, True, False, True]

newarr = arr[x]

print(newarr)

[61 63 65]


In [77]:
import numpy as np

arr = np.array([61, 62, 63, 64, 65])

# 创建一个空列表
filter_arr = []

# 遍历 arr 中的每个元素
for element in arr:
  # 如果元素大于 62，则将值设置为 True，否则为 False：
    if element > 62:
        
        filter_arr.append(True)
    else:
    
   
        filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, False, True, True, True]
[63 64 65]


In [79]:


arr = np.array([1, 2, 3, 4, 5, 6, 7])

# 创建一个空列表
filter_arr = []

# 遍历 arr 中的每个元素
for element in arr:
  # 如果元素可以被 2 整除，则将值设置为 True，否则设置为 False
    if element % 2 == 0:
        filter_arr.append(True)
    else:
        filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, True, False, True, False, True, False]
[2 4 6]


In [80]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

filter_arr = arr % 2 == 0

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False  True False  True False  True False]
[2 4 6]


In [93]:
from numpy import random  #random里没有
x=random.rand() #andom 模块的 rand() 方法返回 0 到 1 之间的随机浮点数。
print(x)
 
    

x = random.rand(5)

print(x)

0.6889349101902058
[0.52254327 0.52796106 0.49321869 0.11226272 0.65357594]


In [90]:
from numpy import random

x=random.randint(100, size=(2,5))

print(x,'\n')
x = random.randint(100, size=(3, 5))

print(x)

[[ 2 40 58 64 23]
 [ 0 67 43 95 50]] 

[[39  6 16 52 42]
 [89 20 69 37 20]
 [72 12 70 96 79]]


In [100]:
#choice() 方法使您可以基于值数组生成随机值。
#choice() 方法将数组作为参数，并随机返回其中一个值。
x = random.choice([3, 5, 7, 9])

print(x)

9


In [102]:
x = random.choice([3, 5, 7, 9], size=(3, 5))

print(x)
#生成由数组参数（3、5、7 和 9）中的值组成的二维数组：

[[5 3 3 7 9]
 [5 9 7 5 7]
 [7 9 9 7 9]]


In [ ]:
为什么要使用 ufuncs？
ufunc 用于在 NumPy 中实现矢量化，这比迭代元素要快得多。

它们还提供广播和其他方法，例如减少、累加等，它们对计算非常有帮助。

ufuncs 还接受其他参数，比如：

where 布尔值数组或条件，用于定义应在何处进行操作。

dtype 定义元素的返回类型。

out 返回值应被复制到的输出数组。

什么是向量化？
将迭代语句转换为基于向量的操作称为向量化。

由于现代 CPU 已针对此类操作进行了优化，因此速度更快。

In [105]:
x = [1, 2, 3, 4]
y = [4, 5, 6, 7]
z = []

for i, j in zip(x, y):
    z.append(i + j)
print(z)

import numpy as np

x = [1, 2, 3, 4]
y = [4, 5, 6, 7]
z = np.add(x, y)

print(z)

[5, 7, 9, 11]
[ 5  7  9 11]
