In [32]:
import numpy as np
arr=np.array([[1,2,2],[1,2,2],[3,4,2]])
print(arr.shape)

(3, 3)


In [1]:
import numpy as np

arr = np.array([1, 2, 3, 4,5], ndmin=7)

print(arr)
print('shape of array :', arr.shape)

[[[[[[[1 2 3 4 5]]]]]]]
shape of array : (1, 1, 1, 1, 1, 1, 5)


In [35]:
# reshape
import numpy  as np
arr=np.array([1,2,3,4,5])
a=arr.reshape(5,1)
print(a)

[[1]
 [2]
 [3]
 [4]
 [5]]


In [16]:
import numpy as np
num=[[1,2,3,4,5],[2,2,2,2,2]]
arr=np.array(num)
a=np.copy(num)
b=arr.view()
print(a)
num.append(1111)
print(num)
print(a.shape)
print(a.base)  #查看来源 
print(b.shape)
print(b.base)

[[1 2 3 4 5]
 [2 2 2 2 2]]
[[1, 2, 3, 4, 5], [2, 2, 2, 2, 2], 1111]
(2, 5)
None
(2, 5)
[[1 2 3 4 5]
 [2 2 2 2 2]]


In [2]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2)

print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [21]:
import numpy as np
arr=np.array([1,2,3,4,5,6])
print(arr.reshape(2,3))
print(arr.reshape(2,3).base)
#上面的例子返回原始数组，因此它是一个视图

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [27]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
newarr = arr.reshape(2, 2,-1) #传递 -1 作为值，NumPy 将为您计算该数字
print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [30]:
# 展平数组
# 展平数组（Flattening the arrays）是指将多维数组转换为 1D 数组。
# 我们可以使用 reshape(-1) 来做到这一点。
# 实例
# 把数组转换为 1D 数组：
arr = np.array([[1, 2, 3], [4, 5, 6]])  #要相同行列的数组
newarr = arr.reshape(-1)
print(newarr)

[1 2 3 4 5 6]


In [31]:
import numpy as np

arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
    print(x)

1
2
3
4
5
6
7
8


In [42]:
import numpy as np
arr = np.array([1, 2, 3])
for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
    print(x)
for x in np.nditer(arr, flags=['buffered'], op_dtypes=['U']):
    print(x)

b'1'
b'2'
b'3'
1
2
3


In [43]:
import numpy as np
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
for idx, x in np.ndenumerate(arr):
    print(idx, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


In [8]:
import numpy as np
arr=np.ones(10)
print(arr)
ar=np.t

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
