In [12]:
import random
x=[]
for i in range(4):
    x.append([])
    for j in range(4):
        a=random.randint(1,100)
        x[i].append(a)
for i in range(4):
    print(x[i])

    

[6, 44, 40, 26]
[6, 86, 22, 26]
[74, 85, 40, 98]
[90, 22, 72, 33]


In [26]:
from random import randint
f=0
while f==0:    
    a=[[randint(1,100) for j in range(4)] for i in range(4)]
    x=[]
    for i in range(4):
        x.append([])
        for j in range(4):
            x[i].append(a[j][0])    
    f=0
    for i in range(4):
        print(a[i])
        n=1
    for j in range(4):
        max1=max(a[i])
        min1=min(x[j])
        if max1==min1:
            print('找到第{}个靶点{}第{}行第{}列'.format(n,max1,i+1,j+1))
            f=1
            print(x)
            print(max(a[i]),min(x[j]))
        n+=1
    if f==0:
        print('没有找到靶点')

    

    


[1, 83, 43, 20]
[85, 28, 50, 31]
[96, 96, 80, 77]
[68, 80, 12, 29]
没有找到靶点
[23, 13, 46, 8]
[100, 60, 8, 78]
[74, 54, 67, 91]
[34, 96, 21, 30]
没有找到靶点
[11, 23, 80, 35]
[46, 41, 18, 45]
[10, 43, 14, 8]
[16, 13, 18, 18]
没有找到靶点
[67, 54, 99, 55]
[56, 98, 30, 82]
[59, 32, 40, 62]
[42, 12, 5, 10]
找到第1个靶点42第4行第1列
[[67, 56, 59, 42], [67, 56, 59, 42], [67, 56, 59, 42], [67, 56, 59, 42]]
42 42
找到第2个靶点42第4行第2列
[[67, 56, 59, 42], [67, 56, 59, 42], [67, 56, 59, 42], [67, 56, 59, 42]]
42 42
找到第3个靶点42第4行第3列
[[67, 56, 59, 42], [67, 56, 59, 42], [67, 56, 59, 42], [67, 56, 59, 42]]
42 42
找到第4个靶点42第4行第4列
[[67, 56, 59, 42], [67, 56, 59, 42], [67, 56, 59, 42], [67, 56, 59, 42]]
42 42


In [305]:
#3.1
import numpy as np
import random
flag=0
while flag==0:
    two_list=[[random.randint(1,100) for i in range(5)] for i in range(5)]
    for i in range(len(two_list)):
        f=0
        list_max=max(two_list[i])
        a=max(two_list[i])
        index=two_list[i].index(list_max)
        for j in range(len(two_list)):         
            if list_max>two_list[j][index]:
                f=1
        if f==0:
            print(np.array(two_list));flag=1
            print('找到鞍点{}，第{}行第{}列'.format(list_max,i+1,index+1))


                
            

[[ 91  72  59  63  15]
 [ 61  18  82   1   5]
 [ 47  59 100  83  12]
 [ 83  42   5  13  23]
 [ 43  35  13  19  43]]
找到鞍点43，第5行第1列


In [302]:
#找鞍点3.0 14行
import numpy as np
import random
two_list=[[random.randint(1,100) for i in range(5)] for i in range(5)]
print(np.array(two_list))
for i in range(len(two_list)):
    f=0
    list_max=max(two_list[i])
    a=max(two_list[i])
    index=two_list[i].index(list_max)
    for j in range(len(two_list)):
        if list_max>two_list[j][index]:
            f+=1
    if f==0:        
        print('找到鞍点{}，第{}行第{}列'.format(list_max,i+1,index+1))

[[ 91  16  57  70  12]
 [ 45  97  39  88  59]
 [ 72  61 100  87  97]
 [  9  75  48  77  78]
 [ 11  63  62  67  27]]
找到鞍点67，第5行第4列
